package angoothape.wallet.di.XMLdi.ResponseHelper;

public class GetTransactionReceiptResponse {
    public String transactionNumber;
    public String transactionDateTime;
    public String sendingAmount;
    public String payInCurrency;
    public String receivingAmount;
    public String payoutCurrency;
    public String commissionCharge;
    public String otherCharge;
    public String vatCharge;
    public String vatPercentage;
    public String totalPayable;
    public String exchangeRate;
    public String purposeOfTransfer;
    public String remitterNo;
    public String remitterName;
    public String remitterContactNo;
    public String remitterAddress;
    public String remitterDOB;
    public String idType;
    public String senderIdNumber;
    public String senderIdExpireDate;
    public String relationWithBeneficiary;
    public String beneficiaryNo;
    public String beneficiaryName;
    public String beneficiaryAddress;
    public String beneficiaryContactNo;
    public String bankName;
    public String bankAccountNo;
    public String bankBranch;
    public String bankAddress;
    public String bankCode;
    public String customerEmail;
    public String payInCountry;
    public String payOutCountry;
    public String earnPoint;
    public String availPoints;
    public String paymentMode;
    public String payoutAgent_Name;
    public String enteredBy;
}
