package ritman.wallet.di.JSONdi.restRequest;

public class CashePreApprovalRequest {
    public Credentials Credentials=new Credentials();

    public String partner_name;
    public String reference_Id;
    public String applicant_id;
    public String loan_amount;
    public String product_type_name;
    public String First_Name;
    public String Last_Name;
    public String DOB;
    public String Gender;
    public String Address_Line_1;
    public String Address_Line_2;
    public String Landmark;
    public String Pincode;
    public String City;
    public String State;
    public String Accommodation;
    public String PAN;
    public String Aadhaar;
    public String Qualification;
    public String residing_with;
    public String number_of_years_at_current_address;
    public String marital_status;
    public String spouse_employment_status;
    public String number_of_kids;
    public String Company_Name;
    public String Office_Phone_no;
    public String Designation;
    public String Monthly_Income;
    public String Number_of_Years_in_Current_Work;
    public String Official_Email;
    public String Office_Add_1;
    public String Office_Add_2;
    public String Landmark_Office;
    public String Office_Pincode;
    public String Office_City;
    public String Office_State;
    public String Working_Since;
    public Integer EmploymentType;
    public Integer Salary_ReceivedTypeId;
    public String work_sector;
    public String job_function;
    public String organization;
    public String BankName;
    public String IFSCCode;
    public String AccountNumber;
    public String PartnerBankName;
    public String PartnerIFSCCode;
    public String PartnerAccNumber;
    public String PartnerRemarks;
    public String CustomerMobile;
    public String Customer_Email;
    public String kyc_co;
    public String kyc_street;
    public String kyc_house;
    public String kyc_lm;
    public String kyc_vtc;
    public String kyc_subdist;
    public String kyc_dist;
    public String kyc_state;
    public String kyc_pc;
    public String kyc_po;
    public String kyc_aadhar_no;
    public String kyc_name;
    public String kyc_dob;
    public String kyc_gender;
    public String kyc_address;

}
