package angoothape.wallet.di.JSONdi.restRequest;

public class esb_hospicare_group_req {
    public String SMS_or_RLE_Branch_Code;
    public String SMS_or_RLE_LG_Code;
    public String DSA_Code;
    public String Branch_Code;
    public String Branch_LG_Code;
    public String Transaction_No;
    public String Date_of_Transaction;
    public String Account_or_Reference_or_Relationship_No;
    public String Application_Number;
    public String Title;
    public String First_Name;
    public String Middle_Name;
    public String Last_Name;
    public String Date_Of_Birth;
    public String Gender;
    public String Adress_Line_1;
    public String Adress_Line_2;
    public String City;
    public String State;
    public String Pincode;
    public String Mobile_Number;
    public String Sum_Assured;
    public String No_of_Hospital_Cash_Benefit_during_term_of_the_policy;
    public Integer Hospital_Cash_Benefit;
    public String Premium_Payment_Frequency;
    public String Instalment_Premium;
    public String Nominee_Name;
    public String Percentage_Share;
    public String DOB_Of_Nominee;
    public String Relationship_with_Member;
    public String Appointee_Name;
    public String Appointee_DOB;
    public String Relationship_with_Nominee;
    public String DOGH_Flag;
    public String OTP_Consent_Flag;
    public String OTP_Consent_Date_Time_Stamp;
    public String Source;
    public String MPH_Name;
    public String Date_Time_Of_Insertion;
    public String Product_Type;
    public String email_ID;
}
